<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-268PN8R" failures="3" tests="8" name="Module Personal Card" time="42.032" errors="0" timestamp="2023-09-20T18:36:20 IST">
  <testcase classname="com.olp.p_card.OLP_R1_OLX_T85_86_1139GCCDOBEnable" name="TC01_navigateToPersonalCard" time="6.723"/>
  <testcase classname="com.olp.p_card.OLP_R1_OLX_T85_86_1139GCCDOBEnable" name="TC02_navigateToResetPassword" time="1.13"/>
  <testcase classname="com.olp.p_card.OLP_R1_OLX_T85_86_1139GCCDOBEnable" name="TC03_ValidateBlankErrorNewPassword" time="0.814"/>
  <testcase classname="com.olp.p_card.OLP_R1_OLX_T85_86_1139GCCDOBEnable" name="TC04_ValidateBlankErrorReTypeNewPassword" time="0.609"/>
  <testcase classname="com.olp.p_card.OLP_R1_OLX_T85_86_1139GCCDOBEnable" name="TC05_ValidateCancelButton" time="0.67"/>
  <testcase classname="com.olp.p_card.OLP_R1_OLX_T85_86_1139GCCDOBEnable" name="TC06_ValidateDOBPasswordAlert" time="3.9">
    <failure type="java.lang.AssertionError" message="Test failed: expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: Test failed: expected [1] but found [0]
at com.olp.p_card.OLP_R1_OLX_T85_86_1139GCCDOBEnable.TC06_ValidateDOBPasswordAlert(OLP_R1_OLX_T85_86_1139GCCDOBEnable.java:247)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC06_ValidateDOBPasswordAlert -->
  <testcase classname="com.olp.p_card.OLP_R1_OLX_T85_86_1139GCCDOBEnable" name="TC07_ValidateRandomDatePasswordAlert" time="3.12">
    <failure type="java.lang.AssertionError" message="Test failed: expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: Test failed: expected [1] but found [0]
at com.olp.p_card.OLP_R1_OLX_T85_86_1139GCCDOBEnable.TC07_ValidateRandomDatePasswordAlert(OLP_R1_OLX_T85_86_1139GCCDOBEnable.java:267)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC07_ValidateRandomDatePasswordAlert -->
  <testcase classname="com.olp.p_card.OLP_R1_OLX_T85_86_1139GCCDOBEnable" name="TC08_NavigateToTraineePersonalCard" time="0.109">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void com.olp.p_card.OLP_R1_OLX_T85_86_1139GCCDOBEnable.TC08_NavigateToTraineePersonalCard(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: TC08_NavigateToTraineePersonalCard([java.lang.String arg0, java.lang.String arg1])
Arguments: [(java.lang.String) patest,(java.lang.String) Assessments,(java.lang.String) 63,(java.lang.String) Last record and Pending status are based on group]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.olp.p_card.OLP_R1_OLX_T85_86_1139GCCDOBEnable.TC08_NavigateToTraineePersonalCard(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: TC08_NavigateToTraineePersonalCard([java.lang.String arg0, java.lang.String arg1])
Arguments: [(java.lang.String) patest,(java.lang.String) Assessments,(java.lang.String) 63,(java.lang.String) Last record and Pending status are based on group]
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- TC08_NavigateToTraineePersonalCard -->
</testsuite> <!-- Module Personal Card -->
